version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "blogs-api-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2870tsibo7qt"
s3_prefix = "blogs-api-challenge"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnvironmentMode=\"dev\""
image_repositories = []
disable_rollback = true
